# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b8e596dbf19d624c16ce2728882940ee1ac96711606a55add02888cd932f7c132901ed7a75c2cac7d9b02e4bad136cf21a153a9ad91ff86a66d969809d803f9

test:
  secret_key_base: 9deda11fdde23aadcc02164e4990148451782d53afa163b0f88bf239189704cd98546e37babbf7e56b074e87475abde2bd94f5865c78c22c3359da005144f7c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
